services:
  app:
    build:
      context: ../..
      dockerfile: docker/production/Dockerfile
      args:
        NODE_ENV: production
        VITE_API_URL: ${VITE_API_URL:-https://abitus-api.geia.vip/v1}
    env_file:
      - ../../.env.production
    ports:
      - "80:80"
    container_name: desafio-mt-app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
